name: Checkout

on:
  workflow_dispatch:
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest # ubuntu-22.04

    strategy:
      matrix:
        java: [17]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: kdevkr/vue-demo
      - name: Checkout submodules
        run: |
          git submodule update --init backend
          cd backend
          git checkout ${GITHUB_REF##*/}

      ###########################################
      ## Java
      ###########################################
      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin # (https://github.com/marketplace/actions/setup-java-jdk#supported-distributions)
          java-version: ${{ matrix.java }}
          architecture: x64
          cache: 'gradle'
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test